print("   anshu".strip())
print("   anshu    ".strip())
print("anshu        ".strip())
print("$$   anshu".strip('$'))
print("$$$anshu$$$".strip('$'))
print("$$$anshu$$$".lstrip('$'))
print("$$$anshu$$$".rstrip('$'))
print("$$$anshu$$$".rstrip('$'))
print("$$$an$hu$$$".strip('$'))
